title: Tensor Core / Tensor Reactions unoffical documentation
description: Something something minion
theme: just-the-docs

url: https://Acen.github.io/Tensor-Dox

aux_links:
  Template Repository: https://github.com/Acen/Tensor-Dox
